apiVersion: apps/v1
kind: Deployment
metadata:
  name: svt-app-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: svt-app-operator
  template:
    metadata:
      labels:
        name: svt-app-operator
    spec:
      serviceAccountName: svt-app-operator
      containers:
        - name: svt-app-operator
          # Replace this with the built image name
          image: quay.io/hongkailiu/svt-app-operator:a011
          command:
          - svt-app-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "svt-app-operator"
